import { Check, ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';
import { products as fallbackProducts } from '../data/products';

const tones = ['terracotta', 'ochre-deep', 'maroon'];
const crops = ['50% 50%', '31% 70%', '72% 66%'];
const productFrames = product => { const images = (product.images?.length ? product.images : [product.image]).slice(0, 3).map((image, i) => ({ image, position: crops[i] })); while (images.length < 3) images.push({ image: product.image, position: crops[images.length] }); return images; };

function ProductCard({ product, index, onAdd, onFly }) {
  const [frame, setFrame] = useState(0); const [added, setAdded] = useState(false); const pointer = useRef(null); const visualRef = useRef(null); const frames = useMemo(() => productFrames(product), [product]); const go = direction => setFrame(current => (current + direction + frames.length) % frames.length);
  const down = event => { pointer.current = { x: event.clientX, y: event.clientY }; event.currentTarget.setPointerCapture?.(event.pointerId); };
  const up = event => { if (!pointer.current) return; const dx = event.clientX - pointer.current.x; const dy = event.clientY - pointer.current.y; pointer.current = null; if (Math.abs(dx) > 42 && Math.abs(dx) > Math.abs(dy)) go(dx < 0 ? 1 : -1); };
  const add = () => { if (!product.variantId || added) return; setAdded(true); onFly(product, visualRef.current, frames[frame]); onAdd(product); window.setTimeout(() => setAdded(false), 1450); };
  return <article className={`product-feature product-editorial ${tones[index]}`}><div className="product-top"><span>0{index + 1} / ZAKAAS ORIGINAL</span><span className="product-price">{product.price ? `₹${Number(product.price).toFixed(0)}` : 'MAHARASHTRA'}</span></div><div className="product-visual product-gallery" ref={visualRef} onPointerDown={down} onPointerUp={up}><div className="product-gallery-track" style={{ transform: `translateX(-${frame * 100}%)` }}>{frames.map((item, imageIndex) => <div className="product-gallery-frame" key={`${item.image}-${imageIndex}`}><img src={item.image} style={{ objectPosition: item.position }} alt={imageIndex === 0 ? `${product.name} ZAKAAS pack` : ''}/></div>)}</div><div className="gallery-controls"><button type="button" onClick={() => go(-1)} aria-label={`Previous ${product.name} image`}><ChevronLeft/></button><span>{String(frame + 1).padStart(2, '0')} <i/> 03</span><button type="button" onClick={() => go(1)} aria-label={`Next ${product.name} image`}><ChevronRight/></button></div></div><div className="product-copy"><small>{product.personality || 'MAHARASHTRA ORIGINAL'}</small><h3>{product.name}</h3><p>“{product.line || product.description || 'A little taste of home.'}”</p><button className={`product-add ${added ? 'is-added' : ''}`} disabled={!product.variantId} onClick={add}>{added ? <>ADDED <Check/></> : <>ADD <Plus/></>}</button></div></article>;
}

export function ProductSection({ onAdd, products = fallbackProducts, live = false }) {
  const [flying, setFlying] = useState(null);
  const fly = (product, visual, frame) => { if (!visual || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const start = visual.getBoundingClientRect(); const bag = document.querySelector('.bag-button')?.getBoundingClientRect(); if (!bag) return; setFlying({ product, image: frame.image, start, bag }); window.requestAnimationFrame(() => window.requestAnimationFrame(() => setFlying(current => current ? { ...current, go: true } : null))); window.setTimeout(() => { setFlying(null); window.dispatchEvent(new CustomEvent('zakaas:add-to-bag')); }, 850); };
  const style = flying ? { '--start-x': `${flying.start.left + flying.start.width * .5}px`, '--start-y': `${flying.start.top + flying.start.height * .63}px`, '--end-x': `${flying.bag.left + flying.bag.width * .5}px`, '--end-y': `${flying.bag.top + flying.bag.height * .5}px` } : {};
  return <section className="products-section" id="shop"><div className="section-intro"><p className="kicker">01 / PICK YOUR PACK {live && '· LIVE FROM SHOPIFY'}</p><h2>WHAT’S YOUR<br/><em>ZAKAAS?</em></h2><p>Three Maharashtra classics. One very loud snack table. Pick your mood, tear it open, pass it around.</p></div><div className="product-rail">{products.slice(0, 3).map((product, index) => <ProductCard key={product.id} product={product} index={index} onAdd={onAdd} onFly={fly}/>)}</div>{flying && <div className={`snack-flight ${flying.go ? 'is-flying' : ''}`} style={style} aria-hidden="true"><img src={flying.image} alt=""/></div>}</section>;
}
